In [1]:
from __future__ import print_function
import numpy as np

In [10]:
whole = np.loadtxt('result/ruc_a_whole.txt',delimiter=' ')
incre = np.loadtxt('result/ruc_A_incre.txt',delimiter=' ')

In [12]:
a = whole[:,-5]
print(a)
np.sort(a)

[-7.28666749e-06 -2.03055806e-05 -6.14607226e-05 ...  1.76316869e-06
  3.52633739e-06  6.97753977e-06]


array([-0.06207637, -0.06102258, -0.05828382, ...,  0.00180077,
        0.00261472,  0.00279301])

首先统计全量更新的a与增量更新的a的描述统计量。

In [13]:
from scipy import stats
stats.describe(whole,axis = None)

DescribeResult(nobs=4626801, minmax=(-25.122300988724017, 28.189424215493535), mean=-0.001354008070825365, variance=0.00954051691999136, skewness=3.11478178695921, kurtosis=13432.924140277462)

In [14]:
stats.describe(incre, axis=None)

DescribeResult(nobs=4626801, minmax=(-24.72486438080449, 30.20843719390757), mean=-0.0014899722006885482, variance=0.010431130085821175, skewness=18.238866671462194, kurtosis=14936.554287981133)

In [15]:
incre_course_num=5
stats.describe(whole[:,-incre_course_num:], axis=None)

DescribeResult(nobs=10755, minmax=(-0.06207636811802894, 0.0027930074252503307), mean=-0.00034235075964795863, variance=4.226836497355902e-06, skewness=-17.28556475896686, kurtosis=392.25638326853624)

In [16]:
incre_course_num=5
stats.describe(incre[:,-incre_course_num:], axis=None)

DescribeResult(nobs=10755, minmax=(-2.3714987516994763, 10.21455460703003), mean=0.02772611310112342, variance=0.058840314814302346, skewness=19.0645876755323, kurtosis=572.2501049930339)

In [8]:
np.sqrt(np.sum(np.square(incre[:,-1]-whole[:,-1])))

6.552224191696876

In [9]:
from preprocessing import read_file
data_file = 'data/ruc.csv'
link_file = 'data/ruc.link'
X, links, concept = read_file(data_file, link_file, dense_input=True)

TypeError: read_file() got an unexpected keyword argument 'dense_input'

In [8]:
concept[1252],concept[-1] = concept[-1],concept[1252]

In [29]:
print('pre concept of {}:'.format(concept[-1]))
print('left is whole-version, right is incremental-version\n')
for i,j in zip(s1,s2):
    print("{}:{:.4f}\t\t{}:{:.4f}".format(concept[i],whole[:,-1][i],concept[j],incre[:,-1][j]))

pre concept of unit_root_test:
left is whole-version, right is incremental-version

probability:1.7609		probability:0.0119
number:0.6579		number:0.0043
markov:0.5701		markov:0.0037
definition:0.5047		definition:0.0033
formula:0.4651		random_variable:0.0030
random_variable:0.4409		formula:0.0030
variance:0.4403		variance:0.0027
markov_chain:0.4067		markov_chain:0.0026
mean:0.3975		equation:0.0024
equation:0.3835		mean:0.0024
parameter:0.3640		parameter:0.0022
stochastic:0.3311		stochastic:0.0021
hypothesis:0.3125		normal_distribution:0.0021
brownian_motion:0.3120		brownian_motion:0.0020
normal_distribution:0.3074		integral:0.0019
integral:0.2846		hypothesis:0.0017
confidence_interval:0.2679		distribution_function:0.0017
estimation:0.2533		confidence_interval:0.0015
average:0.2442		estimation:0.0015
distribution_function:0.2326		average:0.0015
exponential_distribution:0.1953		exponential_distribution:0.0012
statistic:0.1940		finite:0.0012
statistics:0.1883		sequence:0.0012
finite:0.1874	

In [198]:
s1

array([927, 821, 707, ...,  99, 586, 347])

In [45]:
x

array([1, 3, 2])

In [111]:
a = np.loadtxt('result/ruc_A_cgl.txt',delimiter=' ')

In [112]:
a[1252]

array([ 6.38764207e-04, -5.01143938e-05, -2.00602785e-03, ...,
       -3.13631802e-05, -1.78966683e-04,  1.27752841e-03])

In [26]:
print("{:.2f}".format(3.1415926))

3.14
